#!/bin/bash
while getopts d:i:o:rh OPT; do
    case $OPT in
        "d" ) FLG_DIRECTORY="TRUE" ; VAL_DIRECTORY="$OPTARG" ;;
        "i" ) FLG_INTYPE="TRUE" ; VAL_INTYPE="$OPTARG" ;;
        "o" ) FLG_OUTTYPE="TRUE" ; VAL_OUTTYPE="$OPTARG" ;;
        "r" ) FLG_DELETE="TRUE" ;;
        "h" ) FLG_HELP="TRUE" ;;
            * ) echo "OPTIONS: [-d DIRECTORY] [-i TYPE] [-o TYPE] [-r] [-h]" 1>&2
                exit 1 ;;
    esac
done
if [ "$FLG_HELP" = "TRUE" ]; then
    echo "Usage Example: convert -i png -o jpg -d /foo/dir -r"
    echo "i: Input / o: Output / d: Directory / r: Delete source file"
    exit 1
fi
if [ "$(which convert)" = "" ]; then
    echo "ImageMagick をインストールしてください"
    exit 1
fi
if [ "$FLG_INTYPE" != "TRUE" ] || [ "$FLG_OUTTYPE" != "TRUE" ]; then
    echo '対象のファイル形式を指定してください: "-i/-o TYPE"'
    exit 1
fi
if [ "$FLG_DIRECTORY" != "TRUE" ]; then
    VAL_DIRECTORY="."
fi
for TARGET in $(\find $VAL_DIRECTORY -name "*.$VAL_INTYPE"); do
    CONVERT=$(echo $TARGET | sed -e "s/\.[a-zA-Z0-9]*$/\.$VAL_OUTTYPE/")
    echo "Converting $TARGET to $CONVERT …"
    convert $TARGET $CONVERT
    if [ "$FLG_DELETE" = "TRUE" ]; then
        echo "Deleting $TARGET …"
        rm $TARGET
    fi
done
